# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomWidget(object):
    def setupUi(self, CustomWidget):
        CustomWidget.setObjectName("CustomWidget")
        CustomWidget.resize(1400, 700)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(CustomWidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(CustomWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_rashg = QtWidgets.QWidget()
        self.tab_rashg.setObjectName("tab_rashg")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_rashg)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plot_all_polar_rpp = PlotWidget(self.tab_rashg)
        self.plot_all_polar_rpp.setEnabled(True)
        self.plot_all_polar_rpp.setMouseTracking(True)
        self.plot_all_polar_rpp.setObjectName("plot_all_polar_rpp")
        self.gridLayout_6.addWidget(self.plot_all_polar_rpp, 0, 0, 1, 1)
        self.plot_all_polar_rsp = PlotWidget(self.tab_rashg)
        self.plot_all_polar_rsp.setMouseTracking(True)
        self.plot_all_polar_rsp.setObjectName("plot_all_polar_rsp")
        self.gridLayout_6.addWidget(self.plot_all_polar_rsp, 0, 1, 1, 1)
        self.plot_all_polar_rps = PlotWidget(self.tab_rashg)
        self.plot_all_polar_rps.setMouseTracking(True)
        self.plot_all_polar_rps.setObjectName("plot_all_polar_rps")
        self.gridLayout_6.addWidget(self.plot_all_polar_rps, 1, 0, 1, 1)
        self.plot_all_polar_rss = PlotWidget(self.tab_rashg)
        self.plot_all_polar_rss.setMouseTracking(True)
        self.plot_all_polar_rss.setObjectName("plot_all_polar_rss")
        self.gridLayout_6.addWidget(self.plot_all_polar_rss, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_rashg, "")
        self.tab_spect = QtWidgets.QWidget()
        self.tab_spect.setObjectName("tab_spect")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_spect)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plot_all_spect_rpp = PlotWidget(self.tab_spect)
        self.plot_all_spect_rpp.setEnabled(True)
        self.plot_all_spect_rpp.setMouseTracking(True)
        self.plot_all_spect_rpp.setObjectName("plot_all_spect_rpp")
        self.gridLayout_5.addWidget(self.plot_all_spect_rpp, 0, 0, 1, 1)
        self.plot_all_spect_rsp = PlotWidget(self.tab_spect)
        self.plot_all_spect_rsp.setMouseTracking(True)
        self.plot_all_spect_rsp.setObjectName("plot_all_spect_rsp")
        self.gridLayout_5.addWidget(self.plot_all_spect_rsp, 0, 1, 1, 1)
        self.plot_all_spect_rps = PlotWidget(self.tab_spect)
        self.plot_all_spect_rps.setMouseTracking(True)
        self.plot_all_spect_rps.setObjectName("plot_all_spect_rps")
        self.gridLayout_5.addWidget(self.plot_all_spect_rps, 1, 0, 1, 1)
        self.plot_all_spect_rss = PlotWidget(self.tab_spect)
        self.plot_all_spect_rss.setMouseTracking(True)
        self.plot_all_spect_rss.setObjectName("plot_all_spect_rss")
        self.gridLayout_5.addWidget(self.plot_all_spect_rss, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_spect, "")
        self.tab_rpp = QtWidgets.QWidget()
        self.tab_rpp.setObjectName("tab_rpp")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_rpp)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_rpp_polar = PlotWidget(self.tab_rpp)
        self.plot_rpp_polar.setMouseTracking(True)
        self.plot_rpp_polar.setObjectName("plot_rpp_polar")
        self.gridLayout.addWidget(self.plot_rpp_polar, 1, 0, 1, 1)
        self.plot_rpp_spect = PlotWidget(self.tab_rpp)
        self.plot_rpp_spect.setMouseTracking(True)
        self.plot_rpp_spect.setObjectName("plot_rpp_spect")
        self.gridLayout.addWidget(self.plot_rpp_spect, 1, 1, 1, 1)
        self.plot_rpp_polar_exp = PlotWidget(self.tab_rpp)
        self.plot_rpp_polar_exp.setMouseTracking(True)
        self.plot_rpp_polar_exp.setObjectName("plot_rpp_polar_exp")
        self.gridLayout.addWidget(self.plot_rpp_polar_exp, 0, 0, 1, 1)
        self.plot_rpp_spect_exp = PlotWidget(self.tab_rpp)
        self.plot_rpp_spect_exp.setMouseTracking(True)
        self.plot_rpp_spect_exp.setObjectName("plot_rpp_spect_exp")
        self.gridLayout.addWidget(self.plot_rpp_spect_exp, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_rpp, "")
        self.tab_rsp = QtWidgets.QWidget()
        self.tab_rsp.setObjectName("tab_rsp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_rsp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_rsp_polar_exp = PlotWidget(self.tab_rsp)
        self.plot_rsp_polar_exp.setMouseTracking(True)
        self.plot_rsp_polar_exp.setObjectName("plot_rsp_polar_exp")
        self.gridLayout_2.addWidget(self.plot_rsp_polar_exp, 0, 0, 1, 1)
        self.plot_rsp_spect_exp = PlotWidget(self.tab_rsp)
        self.plot_rsp_spect_exp.setMouseTracking(True)
        self.plot_rsp_spect_exp.setObjectName("plot_rsp_spect_exp")
        self.gridLayout_2.addWidget(self.plot_rsp_spect_exp, 0, 1, 1, 1)
        self.plot_rsp_polar = PlotWidget(self.tab_rsp)
        self.plot_rsp_polar.setMouseTracking(True)
        self.plot_rsp_polar.setObjectName("plot_rsp_polar")
        self.gridLayout_2.addWidget(self.plot_rsp_polar, 1, 0, 1, 1)
        self.plot_rsp_spect = PlotWidget(self.tab_rsp)
        self.plot_rsp_spect.setMouseTracking(True)
        self.plot_rsp_spect.setObjectName("plot_rsp_spect")
        self.gridLayout_2.addWidget(self.plot_rsp_spect, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_rsp, "")
        self.tab_rps = QtWidgets.QWidget()
        self.tab_rps.setObjectName("tab_rps")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_rps)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plot_rps_polar_exp = PlotWidget(self.tab_rps)
        self.plot_rps_polar_exp.setMouseTracking(True)
        self.plot_rps_polar_exp.setObjectName("plot_rps_polar_exp")
        self.gridLayout_3.addWidget(self.plot_rps_polar_exp, 0, 0, 1, 1)
        self.plot_rps_spect_exp = PlotWidget(self.tab_rps)
        self.plot_rps_spect_exp.setMouseTracking(True)
        self.plot_rps_spect_exp.setObjectName("plot_rps_spect_exp")
        self.gridLayout_3.addWidget(self.plot_rps_spect_exp, 0, 1, 1, 1)
        self.plot_rps_polar = PlotWidget(self.tab_rps)
        self.plot_rps_polar.setMouseTracking(True)
        self.plot_rps_polar.setObjectName("plot_rps_polar")
        self.gridLayout_3.addWidget(self.plot_rps_polar, 1, 0, 1, 1)
        self.plot_rps_spect = PlotWidget(self.tab_rps)
        self.plot_rps_spect.setMouseTracking(True)
        self.plot_rps_spect.setObjectName("plot_rps_spect")
        self.gridLayout_3.addWidget(self.plot_rps_spect, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_rps, "")
        self.tab_rss = QtWidgets.QWidget()
        self.tab_rss.setObjectName("tab_rss")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_rss)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plot_rss_polar_exp = PlotWidget(self.tab_rss)
        self.plot_rss_polar_exp.setMouseTracking(True)
        self.plot_rss_polar_exp.setObjectName("plot_rss_polar_exp")
        self.gridLayout_4.addWidget(self.plot_rss_polar_exp, 0, 0, 1, 1)
        self.plot_rss_spect_exp = PlotWidget(self.tab_rss)
        self.plot_rss_spect_exp.setMouseTracking(True)
        self.plot_rss_spect_exp.setObjectName("plot_rss_spect_exp")
        self.gridLayout_4.addWidget(self.plot_rss_spect_exp, 0, 1, 1, 1)
        self.plot_rss_polar = PlotWidget(self.tab_rss)
        self.plot_rss_polar.setMouseTracking(True)
        self.plot_rss_polar.setObjectName("plot_rss_polar")
        self.gridLayout_4.addWidget(self.plot_rss_polar, 1, 0, 1, 1)
        self.plot_rss_spect = PlotWidget(self.tab_rss)
        self.plot_rss_spect.setMouseTracking(True)
        self.plot_rss_spect.setObjectName("plot_rss_spect")
        self.gridLayout_4.addWidget(self.plot_rss_spect, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_rss, "")
        self.horizontalLayout_9.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(CustomWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.multiple_reflections = QtWidgets.QCheckBox(self.groupBox)
        self.multiple_reflections.setEnabled(False)
        self.multiple_reflections.setText("")
        self.multiple_reflections.setChecked(True)
        self.multiple_reflections.setObjectName("multiple_reflections")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.multiple_reflections)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.layers = QtWidgets.QComboBox(self.groupBox)
        self.layers.setEnabled(False)
        self.layers.setObjectName("layers")
        self.layers.addItem("")
        self.layers.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.layers)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.box_thickness = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.box_thickness.setEnabled(False)
        self.box_thickness.setMaximum(1000.0)
        self.box_thickness.setSingleStep(0.01)
        self.box_thickness.setProperty("value", 10.0)
        self.box_thickness.setObjectName("box_thickness")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_thickness)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.widget)
        self.groupBox1.setObjectName("groupBox1")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox1)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.box_energy_polar = QtWidgets.QDoubleSpinBox(self.groupBox1)
        self.box_energy_polar.setMinimum(0.0)
        self.box_energy_polar.setMaximum(99.0)
        self.box_energy_polar.setSingleStep(1.0)
        self.box_energy_polar.setProperty("value", 1.7)
        self.box_energy_polar.setObjectName("box_energy_polar")
        self.horizontalLayout_7.addWidget(self.box_energy_polar)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_10 = QtWidgets.QLabel(self.groupBox1)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.box_energy_spect_min = QtWidgets.QDoubleSpinBox(self.groupBox1)
        self.box_energy_spect_min.setEnabled(False)
        self.box_energy_spect_min.setMinimum(0.0)
        self.box_energy_spect_min.setMaximum(20.0)
        self.box_energy_spect_min.setSingleStep(0.01)
        self.box_energy_spect_min.setObjectName("box_energy_spect_min")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_energy_spect_min)
        self.label_11 = QtWidgets.QLabel(self.groupBox1)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.box_energy_spect_max = QtWidgets.QDoubleSpinBox(self.groupBox1)
        self.box_energy_spect_max.setEnabled(False)
        self.box_energy_spect_max.setMaximum(10.0)
        self.box_energy_spect_max.setSingleStep(0.01)
        self.box_energy_spect_max.setProperty("value", 5.0)
        self.box_energy_spect_max.setObjectName("box_energy_spect_max")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_energy_spect_max)
        self.verticalLayout.addWidget(self.groupBox1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sld_angle_theta = QtWidgets.QSlider(self.groupBox_2)
        self.sld_angle_theta.setMinimum(-90)
        self.sld_angle_theta.setMaximum(90)
        self.sld_angle_theta.setProperty("value", 65)
        self.sld_angle_theta.setOrientation(QtCore.Qt.Horizontal)
        self.sld_angle_theta.setObjectName("sld_angle_theta")
        self.horizontalLayout.addWidget(self.sld_angle_theta)
        self.box_angle_theta = QtWidgets.QSpinBox(self.groupBox_2)
        self.box_angle_theta.setPrefix("")
        self.box_angle_theta.setMinimum(-90)
        self.box_angle_theta.setMaximum(90)
        self.box_angle_theta.setProperty("value", 65)
        self.box_angle_theta.setObjectName("box_angle_theta")
        self.horizontalLayout.addWidget(self.box_angle_theta)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sld_angle_phi = QtWidgets.QSlider(self.groupBox_2)
        self.sld_angle_phi.setMaximum(360)
        self.sld_angle_phi.setProperty("value", 30)
        self.sld_angle_phi.setOrientation(QtCore.Qt.Horizontal)
        self.sld_angle_phi.setObjectName("sld_angle_phi")
        self.horizontalLayout_2.addWidget(self.sld_angle_phi)
        self.box_angle_phi = QtWidgets.QSpinBox(self.groupBox_2)
        self.box_angle_phi.setMaximum(360)
        self.box_angle_phi.setProperty("value", 30)
        self.box_angle_phi.setObjectName("box_angle_phi")
        self.horizontalLayout_2.addWidget(self.box_angle_phi)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sld_angle_gamma = QtWidgets.QSlider(self.groupBox_2)
        self.sld_angle_gamma.setMaximum(360)
        self.sld_angle_gamma.setProperty("value", 90)
        self.sld_angle_gamma.setOrientation(QtCore.Qt.Horizontal)
        self.sld_angle_gamma.setObjectName("sld_angle_gamma")
        self.horizontalLayout_3.addWidget(self.sld_angle_gamma)
        self.box_angle_gamma = QtWidgets.QSpinBox(self.groupBox_2)
        self.box_angle_gamma.setMaximum(360)
        self.box_angle_gamma.setProperty("value", 90)
        self.box_angle_gamma.setObjectName("box_angle_gamma")
        self.horizontalLayout_3.addWidget(self.box_angle_gamma)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sld_broad_eps = QtWidgets.QSlider(self.groupBox_3)
        self.sld_broad_eps.setMaximum(50)
        self.sld_broad_eps.setOrientation(QtCore.Qt.Horizontal)
        self.sld_broad_eps.setObjectName("sld_broad_eps")
        self.horizontalLayout_4.addWidget(self.sld_broad_eps)
        self.box_broad_eps = QtWidgets.QSpinBox(self.groupBox_3)
        self.box_broad_eps.setSuffix("")
        self.box_broad_eps.setMaximum(50)
        self.box_broad_eps.setObjectName("box_broad_eps")
        self.horizontalLayout_4.addWidget(self.box_broad_eps)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sld_broad_chi = QtWidgets.QSlider(self.groupBox_3)
        self.sld_broad_chi.setMaximum(50)
        self.sld_broad_chi.setOrientation(QtCore.Qt.Horizontal)
        self.sld_broad_chi.setObjectName("sld_broad_chi")
        self.horizontalLayout_5.addWidget(self.sld_broad_chi)
        self.box_broad_chi = QtWidgets.QSpinBox(self.groupBox_3)
        self.box_broad_chi.setMaximum(50)
        self.box_broad_chi.setObjectName("box_broad_chi")
        self.horizontalLayout_5.addWidget(self.box_broad_chi)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sld_broad_out = QtWidgets.QSlider(self.groupBox_3)
        self.sld_broad_out.setMaximum(50)
        self.sld_broad_out.setProperty("value", 5)
        self.sld_broad_out.setOrientation(QtCore.Qt.Horizontal)
        self.sld_broad_out.setObjectName("sld_broad_out")
        self.horizontalLayout_6.addWidget(self.sld_broad_out)
        self.box_broad_out = QtWidgets.QSpinBox(self.groupBox_3)
        self.box_broad_out.setMaximum(50)
        self.box_broad_out.setProperty("value", 5)
        self.box_broad_out.setObjectName("box_broad_out")
        self.horizontalLayout_6.addWidget(self.box_broad_out)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_9.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(CustomWidget)
        self.tabWidget.setCurrentIndex(0)
        self.box_angle_theta.valueChanged['int'].connect(self.sld_angle_theta.setValue)
        self.sld_angle_theta.valueChanged['int'].connect(self.box_angle_theta.setValue)
        self.sld_angle_phi.valueChanged['int'].connect(self.box_angle_phi.setValue)
        self.box_angle_phi.valueChanged['int'].connect(self.sld_angle_phi.setValue)
        self.sld_angle_gamma.valueChanged['int'].connect(self.box_angle_gamma.setValue)
        self.box_broad_eps.valueChanged['int'].connect(self.sld_broad_eps.setValue)
        self.box_angle_gamma.valueChanged['int'].connect(self.sld_angle_gamma.setValue)
        self.sld_broad_eps.valueChanged['int'].connect(self.box_broad_eps.setValue)
        self.box_broad_chi.valueChanged['int'].connect(self.sld_broad_chi.setValue)
        self.sld_broad_chi.valueChanged['int'].connect(self.box_broad_chi.setValue)
        self.box_broad_out.valueChanged['int'].connect(self.sld_broad_out.setValue)
        self.sld_broad_out.valueChanged['int'].connect(self.box_broad_out.setValue)
        QtCore.QMetaObject.connectSlotsByName(CustomWidget)

    def retranslateUi(self, CustomWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomWidget.setWindowTitle(_translate("CustomWidget", "SHG Yield"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rashg), _translate("CustomWidget", "RA-SHG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spect), _translate("CustomWidget", "Spectra"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rpp), _translate("CustomWidget", "RpP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rsp), _translate("CustomWidget", "RsP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rps), _translate("CustomWidget", "RpS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rss), _translate("CustomWidget", "RsS"))
        self.groupBox.setTitle(_translate("CustomWidget", "Material"))
        self.label_8.setText(_translate("CustomWidget", "Multiple reflections:"))
        self.label_9.setText(_translate("CustomWidget", "Model:"))
        self.layers.setItemText(0, _translate("CustomWidget", "3 Layer"))
        self.layers.setItemText(1, _translate("CustomWidget", "Fresnel"))
        self.label_12.setText(_translate("CustomWidget", "Thickness:"))
        self.box_thickness.setSuffix(_translate("CustomWidget", " nm"))
        self.groupBox1.setTitle(_translate("CustomWidget", "Energy"))
        self.box_energy_polar.setSuffix(_translate("CustomWidget", " eV"))
        self.label.setText(_translate("CustomWidget", "RA-SHG:"))
        self.label_10.setText(_translate("CustomWidget", "Spectra Min:"))
        self.box_energy_spect_min.setSuffix(_translate("CustomWidget", " eV"))
        self.label_11.setText(_translate("CustomWidget", "Spectra Max:"))
        self.box_energy_spect_max.setSuffix(_translate("CustomWidget", " eV"))
        self.groupBox_2.setTitle(_translate("CustomWidget", "Angles"))
        self.label_2.setText(_translate("CustomWidget", "Incidence (θ):"))
        self.box_angle_theta.setSuffix(_translate("CustomWidget", "° "))
        self.label_3.setText(_translate("CustomWidget", "Azimuthal (φ):"))
        self.box_angle_phi.setSuffix(_translate("CustomWidget", "°"))
        self.label_4.setText(_translate("CustomWidget", "Rotation (γ):"))
        self.box_angle_gamma.setSuffix(_translate("CustomWidget", "°"))
        self.groupBox_3.setTitle(_translate("CustomWidget", "Broadening"))
        self.label_5.setText(_translate("CustomWidget", "Epsilon:"))
        self.label_6.setText(_translate("CustomWidget", "Chi2:"))
        self.label_7.setText(_translate("CustomWidget", "Output:"))

from pyqtgraph import PlotWidget
